_target_: src.models.plant_module.PlantDiseaseModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.efficient_net.EfficientNetCustom
  num_classes: 8
  # model_name: "efficientnet-b0"
  dropout_rate: 0.2
  lin1_size: 128
  lin2_size: 64

# compile model for faster training with pytorch 2.0
compile: false
